---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-5.10 
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[yum-vmware-tools::default]
    attributes:
